#!/usr/bin/env bash
# This script transfers a file from a client machine to a remote server using scp.

# It accepts four arguments:
#   1. The path to the file to be transferred.
#   2. The IP address of the server where the file will be copied.
#   3. The username for the SSH connection.
#   4. The path to the SSH private key used for authentication.

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Use scp to securely copy the file to the remote server's home directory (~).
  # Disable strict host key checking for added convenience.
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
