#!/usr/bin/env bash
# This script installs Nginx with the following configurations:
#   - Nginx listens on port 80.
#   - When queried at the root with a curl GET request, it returns a page containing "Holberton School."
#   - Configures a redirection from "/redirect_me" with a "301 Moved Permanently" status code.
#   - Includes a custom 404 page containing "Ceci n'est pas une page."

# Update the package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Create the directory for the HTML content
mkdir -p /etc/nginx/html

# Create an HTML file with "Holberton School" content (not directly related to redirection)
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html

# Create a custom 404 HTML page
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Configure Nginx with a server block that handles redirection and custom error pages
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://google.com/;
    }
    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration
service nginx restart

