#!/usr/bin/env bash
#Description: Displays a list of currently running processes, including those without a TTY, in a user-oriented format showing process hierarchy.
# Script: list_processes.sh

# Use ps command to list all processes for all users and show process hierarchy
ps auxf
