#!/usr/bin/env bash
# Description: Displays a list of currently running processes containing the word "bash," allowing you to easily get the PID of your Bash process.
# Script: list_processes.sh
# shellcheck disable=SC2009

# Use ps command to list all processes for all users and filter lines containing the word "bash"
ps auxf | grep bash
