#!/usr/bin/env bash
# Displays "To infinity and beyond indefinitely" with a sleep of 2 seconds between each iteration of the loop.
# Script: infinity_and_beyond.sh

while true; do
  echo "To infinity and beyond indefinitely"
  sleep 2
done
