#!/usr/bin/env bash
# steps to Stops the 4-to_infinity_and_beyond process.
# Script: 5-dont_stop_me_now

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -z "$pid" ]; then
  echo "The 4-to_infinity_and_beyond process is not running."
else
  # Terminate the process using kill
  kill "$pid"
  echo "The 4-to_infinity_and_beyond process (PID: $pid) has been stopped."
fi
