#!/bin/bash

# Set the input file to be used, in this case, the `/etc/passwd` file
input_file="/etc/passwd"

# Use the IFS (Internal Field Separator) to split lines into fields by the ':' character
IFS=":"

# Read the input file line by line and extract fields
while read -r username x user_id group_id user_info home_directory shell
do
	    # Display the user information in the specified format
	        echo "The user $username is part of the $group_id gang, lives in $home_directory, and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $user_info"
	done < "$input_file"

	# Reset IFS to its default value
	IFS=$' \t\n'
