#!/usr/bin/env bash
# Bash script that creates a whimsical story based on the contents of the `/etc/passwd` file.

# Set the input file to be used, in this case, the `/etc/passwd` file
myfile="/etc/passwd"

# Initialize variables to store fields extracted from each line of the file
f1=""
f2=""
f3=""
f4=""
f5=""
f6=""
f7=""

# Loop through each line of the `/etc/passwd` file
while IFS= read -r line
do
    # Extract specific fields from the line using 'cut'
    f1="$(echo "$line" | cut -d":" -f1)"
    f2="$(echo "$line" | cut -d":" -f4)"
    f3="$(echo "$line" | cut -d":" -f6)"
    f4="$(echo "$line" | cut -d":" -f7)"
    f5="$(echo "$line" | cut -d":" -f3)"
    f6="$(echo "$line" | cut -d":" -f2)"
    f7="$(echo "$line" | cut -d":" -f5)"

    # Create a whimsical story based on the extracted fields
    echo "The user ${f1} is part of the ${f2} gang, lives in ${f3}, and rides ${f4}. ${f5}'s place is protected by the passcode ${f6}, more info about the user here: ${f7}"
done < "$myfile"

