#!/usr/bin/env bash
# This script displays time from 0:01 to 12:59 using a while loop.

hour=0
minute=1

while [ "$hour" -le 12 ]; do
    echo "Hour: $hour"
    while [ "$minute" -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
    minute=1
done
