#!/usr/bin/env bash
# This script displays the content of the current directory with specific formatting.

for file in *; do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
        filename=${file#*-}
        echo "$filename"
    fi
done
